name: CI/CD - Company Service

on:
  push:
    branches: [ main ]

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    permissions:
      contents: write

    env:
      IMAGE_NAME: ${{ secrets.DOCKERHUB_USERNAME }}/company-service

    steps:

      - name: Checkout service repo
        uses: actions/checkout@v4

      - name: Set up JDK 21
        uses: actions/setup-java@v4
        with:
          distribution: 'temurin'
          java-version: '21'

      - name: build the app
        run: |
          mvn clean package -DskipTests


      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}


      - name: Build and push Docker image
        env:
          DOCKERHUB_USERNAME: ${{ secrets.DOCKERHUB_USERNAME }}
          DOCKERHUB_TOKEN: ${{ secrets.DOCKERHUB_TOKEN }}
        run: |
          IMAGE_NAME=$DOCKERHUB_USERNAME/company-service
          IMAGE_TAG=$GITHUB_SHA

          docker login -u $DOCKERHUB_USERNAME -p $DOCKERHUB_TOKEN
          docker build -t $IMAGE_NAME:$IMAGE_TAG .
          docker push $IMAGE_NAME:$IMAGE_TAG

          # Export for later steps
          echo "IMAGE=${IMAGE_NAME}:$IMAGE_TAG" >> $GITHUB_ENV



      - name: Checkout GitOps repo
        uses: actions/checkout@v4
        with:
          repository: KiRa512/jobapp-companyms-deployment  
          token: ${{ secrets.GITOPS_TOKEN }}               
          path: .
          ref: main                                        

      - name: Update image tag in deployment.yaml
        run: |
          IMAGE=$IMAGE_NAME:$GITHUB_SHA
          sed -i "s|image:.*|image: $IMAGE|g" deployment.yaml
          git config user.name "github-actions"
          git config user.email "actions@github.com"
          git add deployment.yaml
          git commit -m "Update company image to $IMAGE"
          git push

