name: CI/CD - Company Service

on:
  push:
    branches: [ main ]

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    permissions:
      contents: write

    env:
      IMAGE_NAME: ${{ secrets.DOCKERHUB_USERNAME }}/company-service

    steps:

      - name: Checkout service repo
        uses: actions/checkout@v4


      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}


      - name: Build and push Docker image
        run: |
          IMAGE_NAME=$DOCKERHUB_USERNAME/company-service
          IMAGE_TAG=${github.sha}
          docker build -t $IMAGE_NAME:$IMAGE_TAG .
          docker push $IMAGE_NAME:$IMAGE_TAG

          # Export for later steps
          echo "IMAGE=${IMAGE_NAME}:$IMAGE_TAG" >> $GITHUB_ENV


      - name: Checkout GitOps repo
        uses: actions/checkout@v4
        with:
          repository: KiRa512/jobapp-deployments   # <-- replace!
          token: ${{ secrets.GITOPS_TOKEN }}               # PAT with repo scope
          path: jobapp-deployments
          ref: main                                        # optional: pin branch

      # -------------------------------------------------
      # 5. Update the image tag inside the Kubernetes manifest
      # -------------------------------------------------
      - name: Update image tag in deployment.yaml
        run: |
          cd jobapp-deployments/company
          sed -i "s|image:.*|image: $IMAGE|g" deployment.yaml
          git config user.name "github-actions"
          git config user.email "actions@github.com"
          git add deployment.yaml
          git commit -m "Update company image to $IMAGE"
          git push

